targets:
  $default:
    sources:
      - doc/**
      - lib/**
      - bin/**
      - test/**
      - pubspec.*
      - $package$
    builders:
      documentation_builder|documentation_builder:
        enabled: True
      
builders:
  style_builder:
    import: "package:style_builder/style_builder.dart"
    builder_factories: ["styleBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
